apiVersion: v1
kind: Service
metadata:
  name: health-monitor-service
  labels:
    app: health-monitor
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: health-monitor